version: "3.1"
services:
  web:
    build:
      context: .
    ports:
      - "80:80"
    restart: always
    entrypoint: /start-reload.sh
    volumes:
      - ./app:/app

  db:
      build:
        context: .
        dockerfile: Dockerfile-db
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: test_db

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8081:8080